import Providers from "@/providers/walletconnect";
import type { Metadata } from "next";
import { poppins } from "../fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers />
      <body className={`${poppins.className}`}>{children}</body>
    </html>
  );
}
